Repository Bella-DeFinTech/uniswap-v3-simulator, pull requests merged in 2021-09, with the labels that each got.

#27 adding tickManager
  src/manager/TickManager.ts
  src/model/Tick.ts
  src/util/LiquidityMath.ts
Labels: breaking-change

#26 add persistence layer
  package.json
  src/client/SimulatorClient.ts
  src/core/ConfigurableCorePool.ts
  src/entity/Snapshot.ts
  src/entity/SnapshotProfile.ts
  src/manager/DBManager.ts
  src/model/PoolState.ts
  src/util/DateConverter.ts
  test/DBManager.test.ts
  yarn.lock
Labels: good first issue, breaking-change

#29 added maxLiquidityPerTick calculations; added overflow check
  src/core/CorePool.ts
  src/enum/FeeAmount.ts
  src/enum/InternalConstants.ts
  src/manager/PositionManager.ts
  src/model/Tick.ts
  src/util/LiquidityMath.ts
  src/util/TickMath.ts
Labels: bug, breaking-change

#35 added initialized check; added clear position
  src/manager/PositionManager.ts
  src/model/Position.ts
Labels: breaking-change

#36 Fix updateposition
  src/core/CorePool.ts
Labels: bug

#37 Add view interface and static swap
  src/core/CorePool.ts
  src/interface/CorePoolView.ts
  src/interface/PositionView.ts
  src/interface/TickView.ts
  src/manager/PositionManager.ts
  src/manager/TickManager.ts
Labels: breaking-change
